/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateListingRouteImport } from './routes/create-listing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialIdRouteImport } from './routes/material.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateListingRoute = CreateListingRouteImport.update({
  id: '/create-listing',
  path: '/create-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIdRoute = MaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-listing': typeof CreateListingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/material/$id': typeof MaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-listing': typeof CreateListingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/material/$id': typeof MaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-listing': typeof CreateListingRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/material/$id': typeof MaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-listing'
    | '/login'
    | '/marketplace'
    | '/my-listings'
    | '/register'
    | '/search'
    | '/material/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-listing'
    | '/login'
    | '/marketplace'
    | '/my-listings'
    | '/register'
    | '/search'
    | '/material/$id'
  id:
    | '__root__'
    | '/'
    | '/create-listing'
    | '/login'
    | '/marketplace'
    | '/my-listings'
    | '/register'
    | '/search'
    | '/material/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateListingRoute: typeof CreateListingRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyListingsRoute: typeof MyListingsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  MaterialIdRoute: typeof MaterialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-listing': {
      id: '/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof CreateListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$id': {
      id: '/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof MaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateListingRoute: CreateListingRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyListingsRoute: MyListingsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  MaterialIdRoute: MaterialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
